### ISSUE TITLE
two modifications

### ISSUE THREAD

**Issue by px172** [jlparkI/RESP#1]
Hi, 

Thanks for sharing your works and codes. I have followed your instructions. During the test I found two errors and made modifications, would you please check them? Many thanks.

in src/model_training/model_training_code.py

def get_wt_score(start_dir):
	...
	x_wt = x[:,29:124,:].flatten(1,-1)
	
the x is not defined, so I changed the x to x_wt to:

def get_wt_score(start_dir):
	...
        x_wt = x_wt[:,29:124,:].flatten(1,-1)

in src/simulated_annealing/run_markov_chains.py	

def analyze_annealing_results(start_dir):
	...
	score_variability = ordmod.extract_hidden_rep(encoded_all,
	
the ordmod and encoded_all are not defined. So I changed the statement to:

def analyze_annealing_results(start_dir):
	...
	score_variability = varbayes_mod.extract_hidden_rep(encoded_seqs,

**Comment by jlparkI** [comment]
Yes, these are both correct, code has been updated. Thanks!
